---
title: "Global Diabetes Journal Club"
site: distill::distill_website
---

Welcome to the Global Diabetes Journal Club (GDJC) website! We aim to sustain a collegial, accessible platform for diabetes researchers, health care providers and the public to connect and learn about recent research across nutritional, clinical and genetic epidemiology as they apply to diabetes. Our members have joined GDJC meetings from 6 continents. 

We run two main programs:

  - **GDJC Talks** Monthly hour-long Zoom meetings that include an article/project presentation and discussion. 
  - **Ad hoc working groups** In Summer 2020, we created two research teams, each of which is preparing a systematic review on an aspect of prevention of type 2 diabetes. 
  
If you want stay updated, please join our mailing list [here](https://groups.google.com/g/global-diabetes-journal-club) where also announce upcoming talks and other relevant events.

Follow us on Twitter @[GDiabetesJC](https://twitter.com/gdiabetesjc)
And see previous talks on our [YouTube channel](https://www.youtube.com/channel/UCdBbu7haaggcoJqmhEx8cdg)

## Upcoming talks

### Research Associate, Alisa Kjaergard - Mendelian randomization: causal inference without intervention

The February 2022 talk is all about Mendelian randomization. Dr. Kjaergaard will introduce the concepts of Mendelian Randomization and use examples from her own work within the field of diabetes and endocrinology.

**Register for the talk February 23, 13-14 UK time [here](insert link)**

This talk is very relevant to those new to the topic of Mendelian Randomization or want to refresh and stay up to date with recent developments.

Her most recent published studies include Mendelian Randomization and regular observational studies investigating the link between [obesity and kidney funtion](https://academic.oup.com/clinchem/advance-article-abstract/doi/10.1093/clinchem/hvab249/6469631?redirectedFrom=fulltext&login=false), [thyroid function and sex hormones](https://link.springer.com/article/10.1007%2Fs10654-021-00721-z) and [homocysteine and female fertility](https://www.nature.com/articles/s41430-021-00898-2).

## Latest GDJC Talk

### Assistant Professor, Leo Martinez - Glycemic trajectories after tuberculosis diagnosis


```{r october-2021, echo=FALSE}

library("vembedr")

embed_url("https://youtu.be/BR98xdpvT5Q")

```

Global Diabetes Journal Club Talk by Assistant Professor Leo Martinez from the Department of Epidemiology at Boston University, Boston, Massachusetts, USA, on how a diagnosis of tuberculosis links with development of diabetes.

A recent [paper](https://doi.org/10.1164/rccm.202007-2634OC) from his group investigated glucose trajectories in patients with newly diagnosed tuberculosis in Eastern China and concluded "Among patients with tuberculosis without diabetes, glycemic changes were common and may represent an important marker for patient response to tuberculosis treatment"

Follow Asst. Prof. Leo Martinez on Twitter @LeoMarti_EpiTB
