---
title: "Systematic Reviews"
author:
  - name: Daniel Ibsen
    affiliation: Steno Diabetes Center Aarhus
    affiliation_url: https://stenoaarhus.dk
  - name: Omar Silverman
    affiliation: Steno Diabetes Center Aarhus
    affiliation_url: https://stenoaarhus.dk
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
---

The Global Diabetes Journal Club encourage global collaborations as part of our mission. We have launched two ad hoc working groups, each work on a systematic review of a topic relevant to diabetes research.

One of the systematic reviews investigates the effectiveness of using telemedicine interventions relevant for primary care setting in prevention of type 2 diabetes.

The other systematic review investigates the availability and performance of risk prediction models for incident type 2 diabetes.

## Effectiveness of telemedicine in prevention of type 2 diabetes: a systematic review and meta-analysis of interventions relevant for primary care settings
The systematic review is registered in [PROSPERO](https://www.crd.york.ac.uk/prospero/display_record.php?ID=CRD42020210829).

The main review question is: What is the effectiveness of using telemedicine interventions relevant for primary care setting in prevention of type 2 diabetes?

We will search for relevant literature in the following databases: MEDLINE, Embase, Scopus, CINAHL, Web of Science, SciELO and LILACS.

### Types of study to be included
We will include all types of intervention studies, including randomized and non-randomized interventions. Observational studies are excluded.

We decided to also include non-randomized interventions to broaden the scope of our review as our preliminary search revealed many recent publications of innovative interventions without a control group.

We will exclude studies that are more than 10 years old (i.e. 2010 and older) because the technologies used 10 years ago are likely outdated and not relevant today.
Condition or domain being studied
Prevention of type 2 diabetes.

### Participants/population
Adults (age ≥18 years) at high risk of developing type 2 diabetes according to the study-specific definition of ‘high risk.’ This includes prediabetes diagnosis, metabolic syndrome, overweight/obesity, and/or use of prediabetes screening tools. Studies including children, people with established type 2 diabetes, type 1 diabetes, gestational diabetes and/or other metabolic or mental health conditions will be excluded.

We decided to be agnostic about the specific definition of high risk of type 2 diabetes because our preliminary search revealed no standardization of this categorization and because all groups would be relevant for prevention of type 2 diabetes.

### Intervention/exposure
Any lifestyle interventions (e.g. diet, physical activity) or medicine (e.g. metformin) delivered using telemedicine, including various mHealth, eHealth and other technologically assisted or conducted interventions. The intervention should be relevant to or take place at a primary health care setting.

We decided to focus on interventions carried out in primary care settings or in settings that resemble primary care settings to best inform which interventions would be relevant, if any, in primary care settings, without necessarily restricting studies to only being carried out in such a setting.

### Comparator/control
There is no restriction on the type of control, but studies will be grouped according to control being: 1) usual care, 2) lifestyle intervention without telemedicine or 3) absent.

We decided to include different types of control groups as these answer different research questions relevant to the main research question.

### Main outcome
Body weight change.

We chose this as the primary outcome because it is clinically relevant and often the outcome that studies base their power calculations on.
Measures of effect
Mean difference.

### Additional outcomes
- Incidence of type 2 diabetes
- Changes in fasting blood glucose
- Changes in HbA1c
- Changes in 2-hour glucose tolerance
- Changes in HOMA-IR
- Changes in blood lipids
- Changes in blood pressure
- Changes in waist circumference

### Review Team
Daniel Ibsen. Department of Public Health, Aarhus University

Camille Mba. MRC Epidemiology Unit, University of Cambridge School of Clinical Medicine, Cambridge, United Kingdom

Elpida Vounzoulaki. Diabetes Research Centre, University of Leicester, United Kingdom

Enzo Cerullo. NIHR Complex Reviews Support Unit, Biostatistics Research Group, University of Leicester, United Kingdom

Harold Torres. Clinica San Felipe, Lima, Peru

Kjell Olsson. Department of Clinical Sciences, Lund University, Sweden

Steven James. School of Nursing, Midwifery and Paramedicine, University of the Sunshine Coast, Petrie, Australia

Raga Ayyagari. Mathematica Policy Research, Princeton, NJ, United States of America

## Title of other systematic

added some extra text

## Risk prediction models for the incidence of type 2 diabetes: A systematic review

## Review team members and their organisational affiliations
Dr Lucy Mrema. National Institute of Medical Research- Mbeya Medical Research Centre NIMR-MMRC
Dr Yogini V Chudasama. Leicester Real World Evidence Unit, Diabetes Research Centre, Leicester General
Hospital, University of Leicester, Leicester, United Kingdom
Dr Arian Malekzadeh. Medical Information Specialist
Dr Iram Faqir Muhammad. Cardiovascular Epidemiology, Department of Clinical Sciences, Lund University,
Malmö, Sweden
Dr Omar Silverman-Retana. Steno Diabetes Center Aarhus, Aarhus University Hospital, Denmark
Ms Laura Van Dongen. Amsterdam UMC, Academic Medical Centre, Department of Cardiology, University of
Amsterdam, Amsterdam Cardiovascular Sciences
Ms Lauren Wedekind. National Institutes of Health

## Review question
What factors are included in risk prediction models that identify incident type 2 diabetes cases, that were published 
by 1 January 2021 (inclusive), in adult populations (aged ≥18 years), and how well do these models perform? 
In validation studies, how do models compare across different study cohorts? 

## Ojectives
To identify studies that developed and assessed risk prediction models for the incidence of type 2 diabetes.

## Specific objectives
1. To identify original studies that developed and assessed risk prediction models for the incidence of type 2 diabetes
   in adult populations and the variables included in each model. To compare the estimated predictive accuracy 
   (e.g. AUC/C-statistic) and reclassification indices (e.g. net reclassification index) of the different prediction models. 
2. To identify studies that validated risk prediction models that were developed in original studies in other cohorts,
   and compare the estimated predictive accuracy and reclassification indices of models in validation studies to those in 
   original studies. 
 
 ## Inclusion criteria 
Studies will be eligible when meeting the following criteria:
1.	the study describes either the development or validation of a prediction model for the incidence of type 2 diabetes,
2.	the population comprised individuals aged 18 years or older from the general population who did not have type 2 diabetes
    at baseline, 
3.  the study describes modelling and evaluation of models using data from a cohort study  ,
4.	the study was published in English, and
5.	the study population used for model development/validation had a minimum follow-up of one year.

## Exclusion criteria
Studies will be excluded when meeting one of the following cirteria:
1.	the study focuses on incidence of diabetes complications or prediabetes,
2.	the study focuses on prediction incidence of comorbidities
3.	qualitative studies

## Type of studies to be included
Primarily cohort studies; case-cohort studies, nested case-control studies

## Main outcome
Incidence of type 2 diabetes

## Search methods for identification of studies  
Databases include MEDLINE, Scopus, Embase and web of science
