---
title: "Want to give a talk?"
output:
  distill::distill_article:
    self_contained: false
---

Planning to practice for your upcoming presentation or defense? Interested in contributing to a community focused on diabetes epidemiology? Consider giving a GDJC Talk!

What we do: 
-	Through GDJC Talks, we aim to provide an opportunity for early-career researchers in diabetes epidemiology to share about their work with GDJC members and any colleagues you’d like to invite to your session. 
-	We promote opportunities for collaboration among our members and aim to invite a diverse group of speakers to give talks on a range of topics across diabetes epidemiology. 
-	We record talks and post them on our [YouTube channel](https://www.youtube.com/channel/UCdBbu7haaggcoJqmhEx8cdg) with captions to promote accessibility and to allow for speakers to include the talk in their research and science communication portfolios.

Format: Each session is one hour, with a 30-45 minute talk, followed by Q&A and discussion of any resources/events of interest to those interested in diabetes epidemiology research. 

If you want to give a talk, please fill out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfS91_dI-2yHk6jl7wiaJAEvIqnDmKjRqBiU3tjANYiME4HHg/viewform), and our team will follow up with you.
